### ISSUE TITLE
Ensure Compatibility with Yoast SEO Premium

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare-pro#11]
1)
PLUGIN COMPATIBILITY PROBLEMS
Yoast SEO compatibility (8883)

-No Updates to counts (8883, 7082)
--Could be from caching
--One uses BuzzSumo extension to compare and received same lack of updates (7082)

-Problem with Yoast SEO and WP Social SEO Pro Open Graph tags overriding Social Warfare (7082)

-Problem with update where caching or CDN tries to load previous or removed file versions (7082)

https://warfareplugins.com/support/open-graph-twitter-cards-yoast-seo/#section_3

**Comment by scott-wiser** [comment]
Yoast Pro Compatibility
Yoasts payed version might use different variables than used in the Pro version
It might be different post meta variables (Lines 113-117 for example) or a different action (used on line 121)
https://github.com/warfare-plugins/social-warfare-pro/blob/master/functions/header-meta-tags.php#L105
