### ISSUE TITLE
Only core share buttons being shown on front-end

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare-pro#3]

**Comment by DustinWStout** [comment]
Styles also not being applied on the front end--they are saving, but not applying.

**Comment by DustinWStout** [comment]
Also minimum share counts not applying. Saving, just not applying.

**Comment by warfare-plugins** [comment]
It appears that on this install, all premium options are being set to their non-premium default values.

**Comment by DustinWStout** [comment]
This is closed, right?

**Comment by warfare-plugins** [comment]
Fixed. Will be part of 2.2 release next week.
